server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

client:
  url: http://172.36.12.3:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
      - action: labelmap
        regex: __syslog_message_sd_(.+)

      # Enable only if needed to reduce cardinality of labels
      #- source_labels: ['__syslog_message_proc_id']
      #  target_label: 'pid'
      #- source_labels: ['__syslog_message_facility']
      #  target_label: 'facility'
