// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	config "github.com/creativeprojects/resticprofile/config"
	mock "github.com/stretchr/testify/mock"
)

// ProfileInfo is an autogenerated mock type for the ProfileInfo type
type ProfileInfo struct {
	mock.Mock
}

type ProfileInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileInfo) EXPECT() *ProfileInfo_Expecter {
	return &ProfileInfo_Expecter{mock: &_m.Mock}
}

// IsAllOptions provides a mock function with no fields
func (_m *ProfileInfo) IsAllOptions() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAllOptions")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ProfileInfo_IsAllOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllOptions'
type ProfileInfo_IsAllOptions_Call struct {
	*mock.Call
}

// IsAllOptions is a helper method to define mock.On call
func (_e *ProfileInfo_Expecter) IsAllOptions() *ProfileInfo_IsAllOptions_Call {
	return &ProfileInfo_IsAllOptions_Call{Call: _e.mock.On("IsAllOptions")}
}

func (_c *ProfileInfo_IsAllOptions_Call) Run(run func()) *ProfileInfo_IsAllOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileInfo_IsAllOptions_Call) Return(_a0 bool) *ProfileInfo_IsAllOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_IsAllOptions_Call) RunAndReturn(run func() bool) *ProfileInfo_IsAllOptions_Call {
	_c.Call.Return(run)
	return _c
}

// IsClosed provides a mock function with no fields
func (_m *ProfileInfo) IsClosed() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClosed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ProfileInfo_IsClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosed'
type ProfileInfo_IsClosed_Call struct {
	*mock.Call
}

// IsClosed is a helper method to define mock.On call
func (_e *ProfileInfo_Expecter) IsClosed() *ProfileInfo_IsClosed_Call {
	return &ProfileInfo_IsClosed_Call{Call: _e.mock.On("IsClosed")}
}

func (_c *ProfileInfo_IsClosed_Call) Run(run func()) *ProfileInfo_IsClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileInfo_IsClosed_Call) Return(_a0 bool) *ProfileInfo_IsClosed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_IsClosed_Call) RunAndReturn(run func() bool) *ProfileInfo_IsClosed_Call {
	_c.Call.Return(run)
	return _c
}

// OtherPropertyInfo provides a mock function with no fields
func (_m *ProfileInfo) OtherPropertyInfo() config.PropertyInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OtherPropertyInfo")
	}

	var r0 config.PropertyInfo
	if rf, ok := ret.Get(0).(func() config.PropertyInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.PropertyInfo)
		}
	}

	return r0
}

// ProfileInfo_OtherPropertyInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OtherPropertyInfo'
type ProfileInfo_OtherPropertyInfo_Call struct {
	*mock.Call
}

// OtherPropertyInfo is a helper method to define mock.On call
func (_e *ProfileInfo_Expecter) OtherPropertyInfo() *ProfileInfo_OtherPropertyInfo_Call {
	return &ProfileInfo_OtherPropertyInfo_Call{Call: _e.mock.On("OtherPropertyInfo")}
}

func (_c *ProfileInfo_OtherPropertyInfo_Call) Run(run func()) *ProfileInfo_OtherPropertyInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileInfo_OtherPropertyInfo_Call) Return(_a0 config.PropertyInfo) *ProfileInfo_OtherPropertyInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_OtherPropertyInfo_Call) RunAndReturn(run func() config.PropertyInfo) *ProfileInfo_OtherPropertyInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Properties provides a mock function with no fields
func (_m *ProfileInfo) Properties() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Properties")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ProfileInfo_Properties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Properties'
type ProfileInfo_Properties_Call struct {
	*mock.Call
}

// Properties is a helper method to define mock.On call
func (_e *ProfileInfo_Expecter) Properties() *ProfileInfo_Properties_Call {
	return &ProfileInfo_Properties_Call{Call: _e.mock.On("Properties")}
}

func (_c *ProfileInfo_Properties_Call) Run(run func()) *ProfileInfo_Properties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileInfo_Properties_Call) Return(_a0 []string) *ProfileInfo_Properties_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_Properties_Call) RunAndReturn(run func() []string) *ProfileInfo_Properties_Call {
	_c.Call.Return(run)
	return _c
}

// PropertyInfo provides a mock function with given fields: name
func (_m *ProfileInfo) PropertyInfo(name string) config.PropertyInfo {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for PropertyInfo")
	}

	var r0 config.PropertyInfo
	if rf, ok := ret.Get(0).(func(string) config.PropertyInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.PropertyInfo)
		}
	}

	return r0
}

// ProfileInfo_PropertyInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PropertyInfo'
type ProfileInfo_PropertyInfo_Call struct {
	*mock.Call
}

// PropertyInfo is a helper method to define mock.On call
//   - name string
func (_e *ProfileInfo_Expecter) PropertyInfo(name interface{}) *ProfileInfo_PropertyInfo_Call {
	return &ProfileInfo_PropertyInfo_Call{Call: _e.mock.On("PropertyInfo", name)}
}

func (_c *ProfileInfo_PropertyInfo_Call) Run(run func(name string)) *ProfileInfo_PropertyInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ProfileInfo_PropertyInfo_Call) Return(_a0 config.PropertyInfo) *ProfileInfo_PropertyInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_PropertyInfo_Call) RunAndReturn(run func(string) config.PropertyInfo) *ProfileInfo_PropertyInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SectionInfo provides a mock function with given fields: name
func (_m *ProfileInfo) SectionInfo(name string) config.SectionInfo {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SectionInfo")
	}

	var r0 config.SectionInfo
	if rf, ok := ret.Get(0).(func(string) config.SectionInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.SectionInfo)
		}
	}

	return r0
}

// ProfileInfo_SectionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SectionInfo'
type ProfileInfo_SectionInfo_Call struct {
	*mock.Call
}

// SectionInfo is a helper method to define mock.On call
//   - name string
func (_e *ProfileInfo_Expecter) SectionInfo(name interface{}) *ProfileInfo_SectionInfo_Call {
	return &ProfileInfo_SectionInfo_Call{Call: _e.mock.On("SectionInfo", name)}
}

func (_c *ProfileInfo_SectionInfo_Call) Run(run func(name string)) *ProfileInfo_SectionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ProfileInfo_SectionInfo_Call) Return(_a0 config.SectionInfo) *ProfileInfo_SectionInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_SectionInfo_Call) RunAndReturn(run func(string) config.SectionInfo) *ProfileInfo_SectionInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Sections provides a mock function with no fields
func (_m *ProfileInfo) Sections() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sections")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ProfileInfo_Sections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sections'
type ProfileInfo_Sections_Call struct {
	*mock.Call
}

// Sections is a helper method to define mock.On call
func (_e *ProfileInfo_Expecter) Sections() *ProfileInfo_Sections_Call {
	return &ProfileInfo_Sections_Call{Call: _e.mock.On("Sections")}
}

func (_c *ProfileInfo_Sections_Call) Run(run func()) *ProfileInfo_Sections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileInfo_Sections_Call) Return(_a0 []string) *ProfileInfo_Sections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_Sections_Call) RunAndReturn(run func() []string) *ProfileInfo_Sections_Call {
	_c.Call.Return(run)
	return _c
}

// TypeName provides a mock function with no fields
func (_m *ProfileInfo) TypeName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProfileInfo_TypeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeName'
type ProfileInfo_TypeName_Call struct {
	*mock.Call
}

// TypeName is a helper method to define mock.On call
func (_e *ProfileInfo_Expecter) TypeName() *ProfileInfo_TypeName_Call {
	return &ProfileInfo_TypeName_Call{Call: _e.mock.On("TypeName")}
}

func (_c *ProfileInfo_TypeName_Call) Run(run func()) *ProfileInfo_TypeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProfileInfo_TypeName_Call) Return(_a0 string) *ProfileInfo_TypeName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileInfo_TypeName_Call) RunAndReturn(run func() string) *ProfileInfo_TypeName_Call {
	_c.Call.Return(run)
	return _c
}

// NewProfileInfo creates a new instance of ProfileInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileInfo {
	mock := &ProfileInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
