project_name: resticprofile

builds:
  - id: darwin_targz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: freebsd_targz
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
    goarm:
      - "6"
      - "7"
  - id: linux_targz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mips64le
      - mipsle
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "6"
      - "7"
  - id: netbsd_targz
    env:
      - CGO_ENABLED=0
    goos:
      - netbsd
    goarch:
      - amd64
  - id: openbsd_targz
    env:
      - CGO_ENABLED=0
    goos:
      - openbsd
    goarch:
      - "386"
      - amd64
  - id: solaris_targz
    env:
      - CGO_ENABLED=0
    goos:
      - solaris
    goarch:
      - amd64
  - id: windows_targz
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - "386"
      - amd64

  - id: resticprofile_zip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm

checksum:
   name_template: 'checksums.txt'
