linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - gocheckcompilerdirectives
    - gosec
    # - maintidx
    - nilnil
    - noctx
    - nolintlint
    # - predeclared
    - reassign
    - sloglint
    - spancheck
    # - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars

linters-settings:
  gosec:
    excludes:
      - G204 # Audit the use of command execution
      - G404 # Insecure random number source (rand)
