linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - gocheckcompilerdirectives
    - gosec
    - maintidx
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - sloglint
    - spancheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars

linters-settings:
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
