project_name: resticprofile
env:
  - RESTIC_VERSION=0.12.1

before:
  hooks:
    - go mod download
    - go generate ./...
    - curl -LO https://github.com/restic/restic/releases/download/v{{ .Env.RESTIC_VERSION }}/restic_{{ .Env.RESTIC_VERSION }}_linux_amd64.bz2
    - bunzip2 restic_{{ .Env.RESTIC_VERSION }}_linux_amd64.bz2
    - mv restic_{{ .Env.RESTIC_VERSION }}_linux_amd64 build/restic
    - chmod +x build/restic

builds:
  - id: resticprofile_targz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: resticprofile_zip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - 386
      - amd64

archives:
  - id: targz
    builds:
    - resticprofile_targz
    format: tar.gz

  - id: zip
    builds:
    - resticprofile_zip
    format: zip
    
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    ids:
    - resticprofile_targz
    image_templates:
    - "creativeprojects/resticprofile:latest"
    - "creativeprojects/resticprofile:{{ .RawVersion }}"
    skip_push: false
    dockerfile: build/Dockerfile
    extra_files:
    - build/restic

brews:
  - 
    name: resticprofile
    ids:
      - targz
    goarm: 6
    tap:
      owner: creativeprojects
      name: "homebrew-tap"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaser
      email: fred@creativeprojects.tech
    folder: Formula
    homepage: https://github.com/creativeprojects/{{ .ProjectName }}
    description: Configuration profiles for restic backup
    license: "GPL-3.0-only"
    custom_block: |
      head "https://github.com/creativeprojects/{{ .ProjectName }}.git"
    dependencies:
      - name: restic
        type: optional
    install: |
      bin.install "{{ .ProjectName }}"
    test: |
      (testpath/"restic_repo").mkdir
      (testpath/"password.txt").write("key")
      (testpath/"profiles.yaml").write <<~EOS
        default:
          repository: "local:#{testpath}/restic_repo"
          password-file: "password.txt"
          initialize: true
      EOS

      (testpath/"testfile").write("This is a testfile")

      system "#{bin}/resticprofile", "backup", "testfile"
      system "#{bin}/resticprofile", "restore", "latest", "-t", "#{testpath}/restore"
      assert compare_file "testfile", "#{testpath}/restore/testfile"

nfpms:
  -
    builds:
      - resticprofile_targz
    formats:
      - apk
      - deb
      - rpm
    vendor: "creativeprojects"
    homepage: "https://github.com/creativeprojects"
    maintainer: "fred@creativeprojects.tech"
    description: "Configuration profiles for restic backup"
    license: "GPL-3.0-only"
    file_name_template: "{{.ProjectName}}_{{.Version}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
    dependencies:
      - restic
    bindir: "/usr/local/bin"
    scripts:
      postinstall: "contrib/posix/post-install.sh"
    contents:
      - { type: config, src: contrib/posix/profiles.conf, dst: /etc/resticprofile/profiles.conf.dist }
      - { type: config, src: contrib/posix/conf.d/backup.conf, dst: /etc/resticprofile/conf.d/backup.conf.dist }
      - { type: config, src: contrib/posix/conf.d/check.conf, dst: /etc/resticprofile/conf.d/check.conf.dist }
      - { type: config, src: contrib/posix/conf.d/hooks.conf, dst: /etc/resticprofile/conf.d/hooks.conf.dist }
      - { type: config, src: contrib/posix/conf.d/metrics.conf, dst: /etc/resticprofile/conf.d/metrics.conf.dist }
      - { type: config, src: contrib/posix/conf.d/prune.conf, dst: /etc/resticprofile/conf.d/prune.conf.dist }
      - { type: config, src: contrib/posix/conf.d/z_overrides.conf, dst: /etc/resticprofile/conf.d/z_overrides.conf.dist }
      - { type: config, src: contrib/posix/profiles.d/fs-snapshot.yaml.sample, dst: /etc/resticprofile/profiles.d/fs-snapshot.yaml.sample }
      - { type: config, src: contrib/posix/profiles.d/minimal.conf.sample, dst: /etc/resticprofile/profiles.d/minimal.conf.sample }
      - { type: config, src: contrib/posix/profiles.d/minimal.yaml.sample, dst: /etc/resticprofile/profiles.d/minimal.yaml.sample }
      - { type: config, src: contrib/posix/profiles.d/system.conf, dst: /etc/resticprofile/profiles.d/system.conf.dist }
      - { type: config, src: contrib/posix/repository.d/default.conf, dst: /etc/resticprofile/repository.d/default.conf.dist }
      - { type: config, src: contrib/posix/repository.d/other.conf.sample, dst: /etc/resticprofile/repository.d/other.conf.sample }
      - { type: config, src: contrib/posix/templates/default-host.conf, dst: /etc/resticprofile/templates/default-host.conf.dist }
      - { type: config, src: contrib/posix/templates/default-tags.conf, dst: /etc/resticprofile/templates/default-tags.conf.dist }
      - { type: config, src: contrib/posix/templates/systemd.timer.in, dst: /etc/resticprofile/templates/systemd.timer.in.dist }
      - { type: config, src: contrib/posix/templates/systemd.unit.in, dst: /etc/resticprofile/templates/systemd.unit.in.dist }
      - src: contrib/posix/resticprofile-send-error.rc
        dst: /etc/resticprofile/resticprofile-send-error.rc.dist
      - src: contrib/notification-scripts/resticprofile-send-error.sh
        dst: /usr/local/bin/resticprofile-send-error
        file_info: { mode: 0755, owner: root, group: root }
