project_name: resticprofile
env:
  - RESTIC_VERSION=0.12.0

before:
  hooks:
    - go mod download
    - go generate ./...
    - curl -LO https://github.com/restic/restic/releases/download/v{{ .Env.RESTIC_VERSION }}/restic_{{ .Env.RESTIC_VERSION }}_linux_amd64.bz2
    - bunzip2 restic_{{ .Env.RESTIC_VERSION }}_linux_amd64.bz2
    - mv restic_{{ .Env.RESTIC_VERSION }}_linux_amd64 build/restic
    - chmod +x build/restic

builds:
  - id: resticprofile_targz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: resticprofile_zip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - 386
      - amd64

archives:
  - id: targz
    builds:
    - resticprofile_targz
    format: tar.gz

  - id: zip
    builds:
    - resticprofile_zip
    format: zip
    
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    ids:
    - resticprofile_targz
    image_templates:
    - "creativeprojects/resticprofile:latest"
    - "creativeprojects/resticprofile:{{ .RawVersion }}"
    skip_push: false
    dockerfile: build/Dockerfile
    extra_files:
    - build/restic
