project_name: resticprofile

version: 2

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: resticprofile_targz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - solaris
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mips64le
      - mipsle
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: riscv64
      - goos: netbsd
        goarch: "386"
      - goos: netbsd
        goarch: arm
      - goos: netbsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: openbsd
        goarch: ppc64

  - id: resticprofile_zip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64

  - id: resticprofile_no_self_update
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=no_self_update
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - id: targz
    ids:
      - resticprofile_targz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats: tar.gz

  - id: targz_no_self_update
    ids:
      - resticprofile_no_self_update
    name_template: '{{ .ProjectName }}_no_self_update_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats: tar.gz

  - id: zip
    ids:
      - resticprofile_zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - 
    name: resticprofile
    ids:
      - targz_no_self_update
    goarm: "6"
    repository:
      owner: creativeprojects
      name: "homebrew-tap"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaser
      email: fred@creativeprojects.tech
    directory: Formula
    homepage: https://github.com/creativeprojects/{{ .ProjectName }}
    description: Configuration profiles for restic backup
    license: "GPL-3.0-only"
    custom_block: |
      head "https://github.com/creativeprojects/{{ .ProjectName }}.git"
    dependencies:
      - name: restic
        type: optional
    install: |
      bin.install "{{ .ProjectName }}"
    test: |
      (testpath/"restic_repo").mkdir
      (testpath/"password.txt").write("key")
      (testpath/"profiles.yaml").write <<~EOS
        default:
          repository: "local:#{testpath}/restic_repo"
          password-file: "password.txt"
          initialize: true
      EOS

      (testpath/"testfile").write("This is a testfile")

      system "#{bin}/resticprofile", "backup", "testfile"
      system "#{bin}/resticprofile", "restore", "latest", "-t", "#{testpath}/restore"
      assert compare_file "testfile", "#{testpath}/restore/testfile"

release:
  draft: true
