with-expecter: true
resolve-type-alias: false
issue-845-fix: true
disable-version-string: true

dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"

packages:
  github.com/creativeprojects/resticprofile/config:
    interfaces:
      ProfileInfo:
      PropertyInfo:
      SectionInfo:
      NamedPropertySet:

  github.com/creativeprojects/resticprofile/schedule:
    interfaces:
      Handler:

  github.com/creativeprojects/resticprofile/monitor:
    interfaces:
      OutputAnalysis:
