ignore:
  - shell/mock/
  - lock/test/
  - priority/check/
  - term/remote.go
  - deprecation.go
  - logger.go
  - systemd.go
  - update.go
  - main.go
  - syslog.go
  - syslog_windows.go

codecov:
  notify:
    after_n_builds: 3

comment:
  after_n_builds: 3

coverage:
  round: nearest
  status:
    project:
      default:
        target: auto
        threshold: "2%"
    patch: 
      default:
        target: "80%"
        threshold: "2%"
