package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/creativeprojects/resticprofile/config"
	"github.com/creativeprojects/resticprofile/term"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const scheduleIntegrationTestsConfiguration = `
version: "2"

global:
  scheduler: crontab:*:%s

groups:
  two-profiles:
    profiles:
      - profile-schedule-inline
      - profile-schedule-struct

profiles:
  default-inline:
    backup:
      schedule-permission: "user"

  default-struct:
    backup:
      schedule:
        permission: "user"

  profile-schedule-inline:
    backup:
      schedule: "*:00,30"

  profile-schedule-struct:
    backup:
      schedule:
        at: "*:00,30"

`

const scheduleIntegrationTestsCrontab = `
### this content was generated by resticprofile, please leave this line intact ###
00,30 * * * *	user	cd /workdir && /home/resticprofile --no-ansi --config config.yaml run-schedule backup@profile
### end of resticprofile content, please leave this line intact ###
`

// TODO: finish implementation of this test
func TestStatusCommandIntegrationUsingCrontab(t *testing.T) {
	crontab := filepath.Join(t.TempDir(), "crontab")
	err := os.WriteFile(crontab, []byte(scheduleIntegrationTestsCrontab), 0o600)
	require.NoError(t, err)

	cfg, err := config.Load(
		bytes.NewBufferString(fmt.Sprintf(scheduleIntegrationTestsConfiguration, crontab)),
		config.FormatYAML,
		config.WithConfigFile("config.yaml"),
	)
	require.NoError(t, err)
	require.NotNil(t, cfg)

	global, err := cfg.GetGlobalSection()
	require.NoError(t, err)
	require.NotNil(t, global)

	testCases := []struct {
		name     string
		contains string
		err      error
	}{
		{
			name: "",
			err:  nil,
		},
		{
			name:     "profile-schedule-inline",
			contains: "Original form: *-*-* *:00,30:00",
		},
		{
			name:     "profile-schedule-struct",
			contains: "Original form: *-*-* *:00,30:00",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			ctx := commandContext{
				Context: Context{
					config: cfg,
					flags: commandLineFlags{
						name: tc.name,
					},
					global: global,
				},
			}
			output := &bytes.Buffer{}
			term.SetOutput(output)
			defer term.SetOutput(os.Stdout)

			err = statusSchedule(output, ctx)
			if tc.err != nil {
				assert.ErrorIs(t, err, tc.err)
				return
			}
			require.NoError(t, err)

			assert.Contains(t, output.String(), tc.contains)
			t.Log(output.String())
		})
	}
}
