{
 "title": "Restic Backup",
 "tags": [
  "backup",
  "health"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "host", "label": "Hosts", "query": "label_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `Added to the repo:`\n        | regexp `.+repo: (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\n)",
     "legendFormat": "Ingested"
    },
    {
     "expr": "sum (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `will delete`    \n        |~ `will delete .+, this frees .+`\n        | regexp `.+this frees (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\nor\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `total prune:`\n        | regexp `total prune: .+ blobs / (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\n)",
     "legendFormat": "Reclaimed"
    }
   ]
  },
  {
   "title": "Ingested Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (data) (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"} \n      |~ \"Files:\" \n      | regexp \"(?P<kind>\\\\w+):.+ (?P<new>\\\\d+) new,\"\n      | label_format data=\"new\", kind=\"{{.kind | ToLower}}\"\n      | unwrap new [$__interval]\n  )\nor\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"} \n      |~ \"Files:\" \n      | regexp \"(?P<kind>\\\\w+):.+ (?P<changed>\\\\d+) changed,\"\n      | label_format data=\"changed\", kind=\"{{.kind | ToLower}}\"\n      | unwrap changed [$__interval]\n  )\n)",
     "legendFormat": "{{data}}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (action) (\n  count_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ ` on profile `\n        |~ `.+ on profile '.+': exit status \\d+`\n        | regexp `(?P<action>\\w+) on .+ exit status (?P<status>\\d+)`\n        | status != 0\n        [$__interval]      \n  )\n)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Backups & Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (action) (\n  count_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `profile '.*': finished`\n        | regexp `.+: finished '(?P<action>\\w+)'`\n        [$__interval]      \n  )\n)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Ingest Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `Added to the repo:`\n        | regexp `.+repo: (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  count_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ ` on profile `\n        |~ `.+ on profile '.+': exit status \\d+`\n        | regexp `.+ on .+ exit status (?P<status>\\d+)`\n        | status != 0\n        [$__interval]      \n  )\nor\n  count_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ ` starting 'backup'`\n        [$__interval]      \n  ) * 0\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Reclaimed Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `will delete`    \n        |~ `will delete .+, this frees .+`\n        | regexp `.+this frees (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\nor\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `total prune:`\n        | regexp `total prune: .+ blobs / (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Time spent with Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `processed`\n        |~ `processed .*files,.+ in \\d+:\\d+:\\d+`\n        | regexp `.+ in (?P<hours>\\d+):(?P<minutes>\\d+):(?P<seconds>\\d+)`\n        | label_format duration=\"{{.hours}}h{{.minutes}}m{{.seconds}}s\"\n        | unwrap duration_seconds(duration)\n        [$__interval]\n  )\nor\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `processed`\n        |~ `processed .*files,.+ in \\d+:\\d+`\n        | regexp `.+ in (?P<minutes>\\d+):(?P<seconds>\\d+)`\n        | label_format duration=\"{{.minutes}}m{{.seconds}}s\"\n        | unwrap duration_seconds(duration)\n        [$__interval]\n  )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Backup Ingest Graph",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `Added to the repo:`\n        | regexp `.+repo: (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Finished Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  count_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ ` finished 'backup'`\n        [$__interval]      \n  )\nor\n  count_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ ` starting 'backup'`\n        [$__interval]      \n  ) * 0\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "New & Changed Files",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (host, data) (\n  sum_over_time(\n    {app=~`^restic.*`,host=~\"(${host:pipe})\"} \n      |~ \"Dirs:|Files:\" \n      | regexp \"(?P<kind>\\\\w+):.+ (?P<changed>\\\\d+) changed,\"\n      | label_format kind=\"{{.kind | ToLower}}\"\n      | unwrap changed [$__interval]\n  )\n)",
     "legendFormat": "{{host}} [C]"
    },
    {
     "expr": "sum by (host, data) (\n  sum_over_time(\n    {app=~`^restic.*`,host=~\"(${host:pipe})\"} \n      |~ \"Dirs:|Files:\" \n      | regexp \"(?P<kind>\\\\w+):.+ (?P<new>\\\\d+) new,\"\n      | label_format kind=\"{{.kind | ToLower}}\"\n      | unwrap new [$__interval]\n  )\n)",
     "legendFormat": "{{host}} [N]"
    }
   ]
  },
  {
   "title": "Reclaimed Space Graph",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `will delete`\n        |~ `will delete .+, this frees .+`\n        | regexp `.+this frees (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\nor\n  sum_over_time(\n    {app=~`^restic.*`, host=~\"(${host:pipe})\"}\n        |~ `total prune:`\n        | regexp `total prune: .+ blobs / (?P<size>[\\d\\.]+ \\w+)`\n        | unwrap bytes(size)[$__interval]\n  )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Finished Backups Vs 14d Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (\n  count_over_time(\n    {app=~`^restic.*`}\n        |~ ` finished 'backup'`\n        [2d]      \n  )\n)\n-\n(sum by (host) (\n  count_over_time(\n    {app=~`^restic.*`}\n        |~ ` finished 'backup'`\n        [14d]      \n  )\n) / 7)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Used Backup Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/share/backup/vol1\"}\n- node_filesystem_free_bytes{mountpoint=\"/share/backup/vol1\"}",
     "legendFormat": "Vol1"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/share/backup/vol1\"}",
     "legendFormat": "Vol1 Size"
    }
   ]
  }
 ]
}