version: '2'

services:
  scheduled-backup:
    image: creativeprojects/resticprofile:${RP_VERSION:-latest}
    container_name: backup_container
    hostname: backup_container
    entrypoint: '/bin/sh'
    command:
      - '-c'
      - 'resticprofile schedule --all && crond -f'
    volumes:
      - ~/.ssh:/root/.ssh
      - './profiles.yaml:/etc/resticprofile/profiles.yaml:ro'
      - './key:/etc/resticprofile/key:ro'
    environment:
      - TZ=Etc/UTC
