
global:
  scheduler: crond

default:
  password-file: key
  repository: "local:/restic_repo"
  initialize: true
  backup:
    source: /source
    exclude-caches: true
    one-file-system: true
    schedule: "*:0,5,55"
    schedule-permission: user
    check-before: true
