#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version = "1"

[global]
  default-command = "snapshots"
  initialize = false
  priority = "low"

[default]
  initialize = false
  password-file = "key"
  repository = "/Volumes/RAMDisk"

  [default.env]
    tmp = "/tmp"

[documents]
  initialize = false
  repository = "~/backup"

  [documents.backup]
    source = "~/Documents"

  [documents.snapshots]
    tag = ["documents"]

[groups]
  full-backup = ["root","src"]

[root]
  inherit = "default"
  initialize = true

  [root.backup]
    exclude-caches = true
    exclude-file = ["root-excludes","excludes"]
    one-file-system = false
    source = ["."]
    tag = ["test","dev"]

  [root.retention]
    after-backup = true
    before-backup = false
    compact = false
    host = true
    keep-daily = 1
    keep-hourly = 1
    keep-last = 3
    keep-monthly = 1
    keep-tag = ["forever"]
    keep-weekly = 1
    keep-within = "3h"
    keep-yearly = 1
    prune = false
    tag = ["test","dev"]

[self]
  initialize = false
  repository = "../backup"

  [self.backup]
    source = "./"

  [self.snapshots]
    tag = ["self"]

[src]
  inherit = "default"
  initialize = true

  [src.backup]
    check-before = true
    exclude = ["/**/.git"]
    exclude-caches = true
    one-file-system = false
    run-after = "echo All Done!"
    run-before = ["echo Starting!","ls -al ~/go"]
    source = ["~/go"]
    tag = ["test","dev"]

  [src.retention]
    after-backup = true
    before-backup = false
    compact = false
    keep-within = "30d"
    prune = true

  [src.snapshots]
    tag = ["test","dev"]

[stdin]
  inherit = "default"

  [stdin.backup]
    stdin = true
    stdin-filename = "stdin-test"
    tag = ["stdin"]

  [stdin.snapshots]
    tag = ["stdin"]
