# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version: "1"

global:
    default-command: snapshots
    initialize: false
    priority: low
    prevent-sleep: true
    # restic-binary: ~/fake_restic
    # legacy-arguments: true
    group-continue-on-error: true

groups:
    full-backup:
    - src
    - root

default:
    description: Contains default parameters like repository and password file
    env:
        tmp: /tmp
    initialize: false
    cleanup-cache: true
    password-file: key
    repository: "/Volumes/RAMDisk/{{ .Profile.Name }}"
    lock: "/Volumes/RAMDisk/resticprofile-{{ .Profile.Name }}.lock"
    copy:
        initialize: true
        initialize-copy-chunker-params: true
        password-file: key
        repository: "/Volumes/RAMDisk/{{ .Profile.Name }}-copy"

repo2:
    description: Copy of default repo
    initialize: true
    password-file: key
    repository: "/Volumes/RAMDisk/{{ .Profile.Name }}"
    init:
      copy-chunker-params: true
      from-repository: "/Volumes/RAMDisk/default"
      from-password-file: key

space:
    description: Repository contains space
    initialize: false
    password-file: key
    repository: "/Volumes/RAMDisk/with space"

documents:
    inherit: default
    backup:
        source: ~/Documents
    initialize: false
    repository: ~/backup/{{ .Hostname }}

root:
    backup:
        schedule: "*:0,15,30,45"
        exclude-caches: true
        exclude-file:
        - root-excludes
        - excludes
        one-file-system: false
        source:
        - .

    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        host: true
        keep-daily: 1
        keep-hourly: 1
        keep-last: 3
        keep-monthly: 1
        keep-tag:
        - forever
        keep-weekly: 1
        keep-within: 3h
        keep-yearly: 1
        prune: false

    forget:
        host: true
        keep-daily: 1
        keep-hourly: 1
        keep-last: 3
        keep-monthly: 1
        keep-tag:
        - forever
        keep-weekly: 1
        keep-within: 3h
        keep-yearly: 1
        prune: false


self:
    force-inactive-lock: true
    initialize: true
    inherit: default
    # status-file: /Volumes/RAMDisk/status.json

    backup:
        extended-status: false
        check-before: false
        no-error-on-warning: true
        source: "{{ .CurrentDir }}"
        exclude:
          - "/**/.git/"
        schedule:
          - "*:00,30"
        schedule-permission: user

    run-after-fail:
      - "echo restic returned an error, command line = ${ERROR_COMMANDLINE}"
      - "echo restic stderr = ${RESTIC_STDERR}"
    check:
        schedule:
          - "*:15"
    retention:
        after-backup: true
    forget:
        schedule: "weekly"
        schedule-priority: standard
    copy:
        initialize: true
        schedule:
          - "*:45"
    snapshots:
        host: true
        run-before: "echo Before snapshots"
        run-after: "echo After snapshots"

syslog:
    force-inactive-lock: true
    initialize: true
    inherit: default

    backup:
        verbose: true
        no-error-on-warning: true
        source: "{{ .CurrentDir }}"
        exclude:
          - "/**/.git/"
        schedule:
          - "*:*"
        schedule-permission: user
        schedule-log: "tcp://localhost:5514"

prom:
    force-inactive-lock: true
    initialize: true
    inherit: default
    prometheus-save-to-file: "self.prom"
    prometheus-push: "http://localhost:9091/"
    prometheus-labels:
      host: "{{ .Hostname }}"
    status-file: /Volumes/RAMDisk/status.json
    backup:
        extended-status: true
        no-error-on-warning: true
        source:
          - "{{ .CurrentDir }}"

system:
    initialize: true
    no-cache: true
    inherit: default
    backup:
        source: ./
        schedule:
        - "*:5,10,20,25,35,40,50,55"
        schedule-permission: system
    forget:
        schedule: "weekly"

src:
    backup:
        check-before: true
        exclude:
        - /**/.git
        exclude-caches: true
        one-file-system: false
        run-after: echo All Done!
        run-before:
        - "echo Hello {{ .Env.LOGNAME }}"
        - "echo current dir: {{ .CurrentDir }}"
        - "echo config dir: {{ .ConfigDir }}"
        # - "echo profile started at {{ .Now.Format "02 Jan 06 15:04 MST" }}"
        source:
        - "{{ .Env.HOME }}/go/src"

    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        keep-within: 30d
        prune: true
       
home:
    inherit: default
    # cache-dir: "${TMPDIR}.restic/"
    backup:
        source: "${HOME}/Projects"

    stream-error:
        -
            pattern: "find-one"
            run: "echo Found One!"
        -
            pattern: "find-two"
            run: "echo Found Two!"

stdin:
    backup:
        stdin: true
        stdin-filename: stdin-test

    inherit: default

stdin-command:
    backup:
        stdin-command:
          - "cat *.go | gzip"
          - "cat shell/*.go | gzip"
        stdin-filename: stdin-test

    inherit: default


dropbox:
    initialize: false
    inherit: default
    backup:
        extended-status: false
        check-before: false
        no-error-on-warning: true
        source: "../../../../../Dropbox"

escape:
    initialize: true
    inherit: default
    backup:
        source:
            - "{{ .CurrentDir }}/examples/private/file with space"
            - "{{ .CurrentDir }}/examples/private/quoted\"file"
            - "{{ .CurrentDir }}/examples/private/Côte d'Ivoire"
        exclude:
            - "**/.git"
            - quoted"file
            - Côte d'Ivoire
    retention:
        after-backup: true
        
nobackup:
    initialize: false
    repository: /Volumes/RAMDisk/{{ .Profile.Name }}
    password-command: echo test
    status-file: /Volumes/RAMDisk/status.json

    copy:
        initialize: false
        repository: /Volumes/RAMDisk/{{ .Profile.Name }}_copy
        password-command2: echo test

copytag:
    inherit: default
    backup:
        source:
            - "."
            - "{{ .CurrentDir }}"
        exclude: "private"

    snapshots:
        tag: true
    forget:
        tag: true
    retention:
        after-backup: true
        tag: true

copypath:
    inherit: default
    backup:
        source:
            - "."
            - "{{ .CurrentDir }}"
            - ".*"
        exclude: "private"
    snapshots:
        path: false
    forget:
        path: true
    retention:
        after-backup: true
        keep-last: 3
        path: true

documents2:
    inherit: documents

run-before-after:
    inherit: default

    snapshots:
        host: true
        run-before: "echo Before snapshots"
        run-after: "echo After snapshots"

tempfile:
    inherit: default

    backup:
        verbose: true
        no-error-on-warning: true
        source: "{{ .CurrentDir }}"
        exclude:
          - "/**/.git/"
        schedule:
          - "*:*"
        schedule-permission: user
        schedule-log: '{{ tempFile "backup.log" }}'
        run-finally: 'cp {{ tempFile "backup.log" }} ./backup{{ .Now.Format "2006-01-02T15-04-05" }}.log'
