global:
    default-command: version
    initialize: false
    priority: low

groups:
    full-backup:
    - root
    - src

default:
    env:
        tmp: /tmp
    initialize: false
    password-file: key
    repository: /Volumes/RAMDisk

documents:
    inherit: default
    backup:
        source: ~/Documents
    initialize: false
    repository: ~/backup
    snapshots:
        tag:
        - documents

root:
    backup:
        schedule: "*:0,15,30,45"
        exclude-caches: true
        exclude-file:
        - root-excludes
        - excludes
        one-file-system: false
        source:
        - .
        tag:
        - test
        - dev
    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        host: true
        keep-daily: 1
        keep-hourly: 1
        keep-last: 3
        keep-monthly: 1
        keep-tag:
        - forever
        keep-weekly: 1
        keep-within: 3h
        keep-yearly: 1
        prune: false
        tag:
        - test
        - dev
    forget:
        host: true
        keep-daily: 1
        keep-hourly: 1
        keep-last: 3
        keep-monthly: 1
        keep-tag:
        - forever
        keep-weekly: 1
        keep-within: 3h
        keep-yearly: 1
        prune: false
        tag:
        - test
        - dev

self:
    lock: "/Volumes/RAMDisk/resticprofile-profile-self.lock"
    force-inactive-lock: true
    initialize: true
    inherit: default
    status-file: status.json
    backup:
        check-before: true
        source: ./
        schedule:
        - "*:00,30"
        schedule-permission: user
    check:
        schedule:
        - "*:15,45"

system:
    initialize: true
    inherit: default
    backup:
        source: ./
        schedule:
        - "*:5,10,20,25,35,40,50,55"
        schedule-permission: system

src:
    lock: "/tmp/resticprofile-profile-src.lock"
    backup:
        check-before: true
        exclude:
        - /**/.git
        exclude-caches: true
        one-file-system: false
        run-after: echo All Done!
        run-before:
        - echo Starting!
        - ls -al ~/go
        source:
        - ~/go
        tag:
        - test
        - dev
    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        keep-within: 30d
        prune: true
    snapshots:
        tag:
        - test
        - dev
        
stdin:
    backup:
        stdin: true
        stdin-filename: stdin-test
        tag:
        - stdin
    inherit: default
    snapshots:
        tag:
        - stdin
