{{ define "tags" }}
        tag:
        - dev
        - {{ .Profile.Name }}
{{ end }}

global:
    default-command: snapshots
    initialize: false
    priority: low
    # restic-binary: ~/fake_restic

groups:
    full-backup:
    - root
    - src

default:
    description: Contains default parameters like repository and password file
    env:
        tmp: /tmp
    initialize: false
    password-file: key
    repository: "/Volumes/RAMDisk/{{ .Profile.Name }}"
    lock: "/Volumes/RAMDisk/resticprofile-{{ .Profile.Name }}.lock"

space:
    description: Repository contains space
    initialize: false
    password-file: key
    repository: "/Volumes/RAMDisk/with space"

documents:
    inherit: default
    backup:
        source: ~/Documents
    initialize: false
    repository: ~/backup/{{ .Hostname }}
    snapshots:
        {{ template "tags" . }}

root:
    backup:
        schedule: "*:0,15,30,45"
        exclude-caches: true
        exclude-file:
        - root-excludes
        - excludes
        one-file-system: false
        source:
        - .
        {{ template "tags" . }}
    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        host: true
        keep-daily: 1
        keep-hourly: 1
        keep-last: 3
        keep-monthly: 1
        keep-tag:
        - forever
        keep-weekly: 1
        keep-within: 3h
        keep-yearly: 1
        prune: false
        {{ template "tags" . }}
    forget:
        host: true
        keep-daily: 1
        keep-hourly: 1
        keep-last: 3
        keep-monthly: 1
        keep-tag:
        - forever
        keep-weekly: 1
        keep-within: 3h
        keep-yearly: 1
        prune: false
        {{ template "tags" . }}

self:
    force-inactive-lock: true
    initialize: true
    inherit: default
    status-file: /Volumes/RAMDisk/status.json
    backup:
        extended-status: false
        check-before: false
        no-error-on-warning: true
        source: {{ .CurrentDir }}
        exclude:
          - "/**/.git/"
        schedule:
          - "*:00,30"
        schedule-permission: user
        {{ template "tags" . }}
    run-after-fail:
      - "echo restic returned an error, command line = ${ERROR_COMMANDLINE}"
      - "echo restic stderr = ${RESTIC_STDERR}"
    check:
        schedule:
          - "*:15,45"
    retention:
        after-backup: true
    forget:
        schedule: "weekly"
        schedule-priority: standard

prom:
    force-inactive-lock: true
    initialize: true
    inherit: default
    prometheus-save-to-file: "self.prom"
    backup:
        extended-status: true
        no-error-on-warning: true
        source: {{ .CurrentDir }}
        {{ template "tags" . }}

system:
    initialize: true
    no-cache: true
    inherit: default
    backup:
        source: ./
        schedule:
        - "*:5,10,20,25,35,40,50,55"
        schedule-permission: system
    forget:
        schedule: "weekly"

src:
    backup:
        check-before: true
        exclude:
        - /**/.git
        exclude-caches: true
        one-file-system: false
        run-after: echo All Done!
        run-before:
        - "echo Hello {{ .Env.LOGNAME }}"
        - "echo current dir: {{ .CurrentDir }}"
        - "echo config dir: {{ .ConfigDir }}"
        - "echo profile started at {{ .Now.Format "02 Jan 06 15:04 MST" }}"
        source:
        - "{{ .Env.HOME }}/go/src"
        {{ template "tags" . }}
    inherit: default
    initialize: true
    retention:
        after-backup: true
        before-backup: false
        compact: false
        keep-within: 30d
        prune: true
    snapshots:
        {{ template "tags" . }}
        
stdin:
    backup:
        stdin: true
        stdin-filename: stdin-test
        {{ template "tags" . }}
    inherit: default
    snapshots:
        {{ template "tags" . }}

dropbox:
    initialize: false
    inherit: default
    initialize: false
    backup:
        extended-status: false
        check-before: false
        no-error-on-warning: true
        source: "../../../../../Dropbox"
