[default]
repository = "rest:http://user:password@localhost:8000/path"
password-file = "key"

[simple]
inherit = "default"
[simple.backup]
exclude = "/**/.git"
source = "/source"

[spaces]
inherit = "default"
password-file = "different key"
[spaces.backup]
exclude = "My Documents"
source = "/source dir"

[quotes]
inherit = "default"
[quotes.backup]
exclude = ["My'Documents", "My\"Documents"]
source = ["/source'dir", "/source\"dir"]

[glob1]
inherit = "default"
[glob1.backup]
exclude = ["[aA]*"]
source = ["/source"]

[glob2]
inherit = "default"
[glob2.backup]
exclude = ["examples/integration*"]
source = ["examples/integration*"]

[mixed]
inherit = "default"
[mixed.backup]
source = ["/Côte d'Ivoire", "/path/with space; echo foo'"]

[fix]
inherit = "default"
password-file = "different\\ key"
[fix.backup]
exclude = "My\\ Documents"
source = "/source\\ dir"