// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewOutputAnalysis creates a new instance of OutputAnalysis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutputAnalysis(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutputAnalysis {
	mock := &OutputAnalysis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OutputAnalysis is an autogenerated mock type for the OutputAnalysis type
type OutputAnalysis struct {
	mock.Mock
}

type OutputAnalysis_Expecter struct {
	mock *mock.Mock
}

func (_m *OutputAnalysis) EXPECT() *OutputAnalysis_Expecter {
	return &OutputAnalysis_Expecter{mock: &_m.Mock}
}

// ContainsRemoteLockFailure provides a mock function for the type OutputAnalysis
func (_mock *OutputAnalysis) ContainsRemoteLockFailure() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContainsRemoteLockFailure")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// OutputAnalysis_ContainsRemoteLockFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainsRemoteLockFailure'
type OutputAnalysis_ContainsRemoteLockFailure_Call struct {
	*mock.Call
}

// ContainsRemoteLockFailure is a helper method to define mock.On call
func (_e *OutputAnalysis_Expecter) ContainsRemoteLockFailure() *OutputAnalysis_ContainsRemoteLockFailure_Call {
	return &OutputAnalysis_ContainsRemoteLockFailure_Call{Call: _e.mock.On("ContainsRemoteLockFailure")}
}

func (_c *OutputAnalysis_ContainsRemoteLockFailure_Call) Run(run func()) *OutputAnalysis_ContainsRemoteLockFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OutputAnalysis_ContainsRemoteLockFailure_Call) Return(b bool) *OutputAnalysis_ContainsRemoteLockFailure_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *OutputAnalysis_ContainsRemoteLockFailure_Call) RunAndReturn(run func() bool) *OutputAnalysis_ContainsRemoteLockFailure_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteLockedBy provides a mock function for the type OutputAnalysis
func (_mock *OutputAnalysis) GetRemoteLockedBy() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteLockedBy")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// OutputAnalysis_GetRemoteLockedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteLockedBy'
type OutputAnalysis_GetRemoteLockedBy_Call struct {
	*mock.Call
}

// GetRemoteLockedBy is a helper method to define mock.On call
func (_e *OutputAnalysis_Expecter) GetRemoteLockedBy() *OutputAnalysis_GetRemoteLockedBy_Call {
	return &OutputAnalysis_GetRemoteLockedBy_Call{Call: _e.mock.On("GetRemoteLockedBy")}
}

func (_c *OutputAnalysis_GetRemoteLockedBy_Call) Run(run func()) *OutputAnalysis_GetRemoteLockedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OutputAnalysis_GetRemoteLockedBy_Call) Return(s string, b bool) *OutputAnalysis_GetRemoteLockedBy_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *OutputAnalysis_GetRemoteLockedBy_Call) RunAndReturn(run func() (string, bool)) *OutputAnalysis_GetRemoteLockedBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteLockedMaxWait provides a mock function for the type OutputAnalysis
func (_mock *OutputAnalysis) GetRemoteLockedMaxWait() (time.Duration, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteLockedMaxWait")
	}

	var r0 time.Duration
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Duration, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// OutputAnalysis_GetRemoteLockedMaxWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteLockedMaxWait'
type OutputAnalysis_GetRemoteLockedMaxWait_Call struct {
	*mock.Call
}

// GetRemoteLockedMaxWait is a helper method to define mock.On call
func (_e *OutputAnalysis_Expecter) GetRemoteLockedMaxWait() *OutputAnalysis_GetRemoteLockedMaxWait_Call {
	return &OutputAnalysis_GetRemoteLockedMaxWait_Call{Call: _e.mock.On("GetRemoteLockedMaxWait")}
}

func (_c *OutputAnalysis_GetRemoteLockedMaxWait_Call) Run(run func()) *OutputAnalysis_GetRemoteLockedMaxWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OutputAnalysis_GetRemoteLockedMaxWait_Call) Return(duration time.Duration, b bool) *OutputAnalysis_GetRemoteLockedMaxWait_Call {
	_c.Call.Return(duration, b)
	return _c
}

func (_c *OutputAnalysis_GetRemoteLockedMaxWait_Call) RunAndReturn(run func() (time.Duration, bool)) *OutputAnalysis_GetRemoteLockedMaxWait_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteLockedSince provides a mock function for the type OutputAnalysis
func (_mock *OutputAnalysis) GetRemoteLockedSince() (time.Duration, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteLockedSince")
	}

	var r0 time.Duration
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Duration, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// OutputAnalysis_GetRemoteLockedSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteLockedSince'
type OutputAnalysis_GetRemoteLockedSince_Call struct {
	*mock.Call
}

// GetRemoteLockedSince is a helper method to define mock.On call
func (_e *OutputAnalysis_Expecter) GetRemoteLockedSince() *OutputAnalysis_GetRemoteLockedSince_Call {
	return &OutputAnalysis_GetRemoteLockedSince_Call{Call: _e.mock.On("GetRemoteLockedSince")}
}

func (_c *OutputAnalysis_GetRemoteLockedSince_Call) Run(run func()) *OutputAnalysis_GetRemoteLockedSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OutputAnalysis_GetRemoteLockedSince_Call) Return(duration time.Duration, b bool) *OutputAnalysis_GetRemoteLockedSince_Call {
	_c.Call.Return(duration, b)
	return _c
}

func (_c *OutputAnalysis_GetRemoteLockedSince_Call) RunAndReturn(run func() (time.Duration, bool)) *OutputAnalysis_GetRemoteLockedSince_Call {
	_c.Call.Return(run)
	return _c
}
