// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/creativeprojects/resticprofile/monitor"
	mock "github.com/stretchr/testify/mock"
)

// NewReceiver creates a new instance of Receiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Receiver {
	mock := &Receiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Receiver is an autogenerated mock type for the Receiver type
type Receiver struct {
	mock.Mock
}

type Receiver_Expecter struct {
	mock *mock.Mock
}

func (_m *Receiver) EXPECT() *Receiver_Expecter {
	return &Receiver_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type Receiver
func (_mock *Receiver) Start(command string) {
	_mock.Called(command)
	return
}

// Receiver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Receiver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - command string
func (_e *Receiver_Expecter) Start(command interface{}) *Receiver_Start_Call {
	return &Receiver_Start_Call{Call: _e.mock.On("Start", command)}
}

func (_c *Receiver_Start_Call) Run(run func(command string)) *Receiver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Receiver_Start_Call) Return() *Receiver_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *Receiver_Start_Call) RunAndReturn(run func(command string)) *Receiver_Start_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function for the type Receiver
func (_mock *Receiver) Status(status monitor.Status) {
	_mock.Called(status)
	return
}

// Receiver_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type Receiver_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - status monitor.Status
func (_e *Receiver_Expecter) Status(status interface{}) *Receiver_Status_Call {
	return &Receiver_Status_Call{Call: _e.mock.On("Status", status)}
}

func (_c *Receiver_Status_Call) Run(run func(status monitor.Status)) *Receiver_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 monitor.Status
		if args[0] != nil {
			arg0 = args[0].(monitor.Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Receiver_Status_Call) Return() *Receiver_Status_Call {
	_c.Call.Return()
	return _c
}

func (_c *Receiver_Status_Call) RunAndReturn(run func(status monitor.Status)) *Receiver_Status_Call {
	_c.Run(run)
	return _c
}

// Summary provides a mock function for the type Receiver
func (_mock *Receiver) Summary(command string, summary monitor.Summary, stderr string, result error) {
	_mock.Called(command, summary, stderr, result)
	return
}

// Receiver_Summary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summary'
type Receiver_Summary_Call struct {
	*mock.Call
}

// Summary is a helper method to define mock.On call
//   - command string
//   - summary monitor.Summary
//   - stderr string
//   - result error
func (_e *Receiver_Expecter) Summary(command interface{}, summary interface{}, stderr interface{}, result interface{}) *Receiver_Summary_Call {
	return &Receiver_Summary_Call{Call: _e.mock.On("Summary", command, summary, stderr, result)}
}

func (_c *Receiver_Summary_Call) Run(run func(command string, summary monitor.Summary, stderr string, result error)) *Receiver_Summary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 monitor.Summary
		if args[1] != nil {
			arg1 = args[1].(monitor.Summary)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Receiver_Summary_Call) Return() *Receiver_Summary_Call {
	_c.Call.Return()
	return _c
}

func (_c *Receiver_Summary_Call) RunAndReturn(run func(command string, summary monitor.Summary, stderr string, result error)) *Receiver_Summary_Call {
	_c.Run(run)
	return _c
}
