name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.25']
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go_version }}

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout=30m

      - name: Test
        run: make test-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make build

      - name: Code coverage with codecov
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,GO
          file: ./coverage.out
          flags: unittests
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
