name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.26']
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go_version }}

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          args: --timeout=30m

      - name: Test
        run: make test-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make build

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          env_vars: OS,GO
          files: ./coverage.out,./unit-tests.xml
          flags: unittests
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v6
        with:
          env_vars: OS,GO
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./unit-tests.xml
