name: Rebuild docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '32 6 * * 0'


jobs:
  docker:
    name: Rebuild docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: .github/workflows/env
          log-variables: true

      - name: Checkout latest tag
        id: version
        run: |
          export LATEST_TAG=$(git tag --list 'v*' --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            echo "No release tag found"
            exit 1
          fi
          git checkout $LATEST_TAG
          echo "version=${LATEST_TAG#v}" >> "$GITHUB_OUTPUT"
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: ./.github/actions/docker-build
        with:
          go-version: ${{ steps.dotenv.outputs.go_version }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: |
            creativeprojects/resticprofile:latest
            creativeprojects/resticprofile:${{ steps.version.outputs.version }}
            ghcr.io/creativeprojects/resticprofile:latest
            ghcr.io/creativeprojects/resticprofile:${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.version.outputs.created }}
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
