name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: .github/workflows/env
          log-variables: true

      - name: Set up Go ${{ steps.dotenv.outputs.go_version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.dotenv.outputs.go_version }}
          check-latest: true
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: .github/workflows/env
          log-variables: true

      - name: Image metadata
        id: meta
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: ./.github/actions/docker-build
        with:
          go-version: ${{ steps.dotenv.outputs.go_version }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: |
            creativeprojects/resticprofile:latest
            creativeprojects/resticprofile:${{ steps.meta.outputs.version }}
            ghcr.io/creativeprojects/resticprofile:latest
            ghcr.io/creativeprojects/resticprofile:${{ steps.meta.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
