name: Run tests workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      go_version:
        required: true
        type: string
      lint_version:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  build:
    name: Build and run test on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    env:
      OS: ${{ inputs.os }}
      GO: ${{ inputs.go_version }}

    steps:
      - name: Set up Go ${{ inputs.go_version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go_version }}
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ inputs.lint_version }}
          args: --timeout=30m

      - name: Build
        run: make build

      - name: Test
        run: make test-ci
        env:
          TEST_FUSE: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          name: code-coverage-report-${{ matrix.os }}
          env_vars: OS,GO
          files: ./coverage.out
          flags: unittests
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v6
        with:
          env_vars: OS,GO
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./unit-tests.xml
