name: Publish snapshot to docker hub

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: .github/workflows/env
          log-variables: true

      - name: Build and push image
        uses: ./.github/actions/docker-build
        with:
          go-version: ${{ steps.dotenv.outputs.go_version }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: |
            creativeprojects/resticprofile:nightly
            ghcr.io/creativeprojects/resticprofile:nightly
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
