name: Publish snapshot to docker hub

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.24
          check-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install eget
        run: go install github.com/zyedidia/eget@latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --snapshot --config .goreleaser-snapshot.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to DockerHub
        shell: bash
        run: |
          docker push creativeprojects/resticprofile:nightly-arm64v8
          docker push creativeprojects/resticprofile:nightly-amd64
          docker manifest create "creativeprojects/resticprofile:nightly" \
            --amend "creativeprojects/resticprofile:nightly-amd64" \
            --amend "creativeprojects/resticprofile:nightly-arm64v8"
          docker manifest inspect "creativeprojects/resticprofile:nightly"
          docker manifest push "creativeprojects/resticprofile:nightly"

      - name: Publish to GitHub Container Registry
        shell: bash
        run: |
          docker push ghcr.io/creativeprojects/resticprofile:nightly-arm64v8
          docker push ghcr.io/creativeprojects/resticprofile:nightly-amd64
          docker manifest create "ghcr.io/creativeprojects/resticprofile:nightly" \
            --amend "ghcr.io/creativeprojects/resticprofile:nightly-amd64" \
            --amend "ghcr.io/creativeprojects/resticprofile:nightly-arm64v8"
          docker manifest inspect "ghcr.io/creativeprojects/resticprofile:nightly"
          docker manifest push "ghcr.io/creativeprojects/resticprofile:nightly"
