name: Test on Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '!github/workflows/windows.yml'

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '!github/workflows/windows.yml'

jobs:
  build:
    name: Build and run tests on Windows
    uses: ./.github/workflows/run-tests-os.yml
    with:
      os: 'windows-latest'
    secrets: inherit
